name: wwwpy_gong
services:
  wwwpy-gong-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
#    network_mode: host
    container_name: wwwpy-gong-container
    volumes:
      - ..:/repo
    working_dir: /repo
    command: /bin/bash -c "./docker/entrypoint.sh"
    ports:
      - "8100:8000"
